fix: added kratos logs for debug

diff --git a/.github/workflows/test-build-push-api.yaml b/.github/workflows/test-build-push-api.yaml
--- a/.github/workflows/test-build-push-api.yaml
+++ b/.github/workflows/test-build-push-api.yaml
@@ -99,9 +99,19 @@ jobs:
       - name: Wait for Ory Kratos to be Ready
         run: |
           for i in {1..10}; do
-            curl -f http://localhost:4433/health && break || sleep 2
+            if curl -f http://localhost:4433/health; then
+              echo "Kratos is ready"
+              exit 0
+            else
+              echo "Waiting for Kratos..."
+              sleep 2
+            fi
           done
-        timeout-minutes: 5
+
+          echo "❌ Kratos failed to start. Dumping logs..."
+          docker logs kratos
+          exit 1
+
 
       - name: Install Dependencies
         run: |
